### ISSUE TITLE
What IS this?

### ISSUE THREAD

**Issue by MichaelHinrichs** [aedenthorn/SWPTMods#11]
I don't remember when or why I starred this. There is no description or readme.mb. And I can't figure anything out by looking at the code. What the heck does SWPT stand for?

**Comment by aedenthorn** [comment]
it stands for She Will Punish Them, an abandoned Unity game

**Comment by MichaelHinrichs** [comment]
WHY THE HECK DID I STAR THIS??? I must have missclicked or something. I don't remember this at all! I'v never even heard of this game.
